name: Trigger auto deployment for open-webui

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/open-webui-AutoDeployTrigger-78e700d5-4ef4-4971-93f8-b06af28f6cda.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.OPENWEBUI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.OPENWEBUI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.OPENWEBUI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.OPENWEBUI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.OPENWEBUI_REGISTRY_PASSWORD }}
          containerAppName: open-webui
          resourceGroup: OpenAI
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


